import React from 'react'
import Head from 'next/head'
import {useStateValue} from "@/content/StateContent";

const Layout = ({children}) => {
    const {showCart, setShowCart} = useStateValue();
    return (
        <>
            <div className={'layout'}>
                <Head>
                    <title>Boutique</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                {
                    showCart && <div className={'overlay'} onClick={() => setShowCart(false)}></div>
                }
                <main>
                    {children}
                </main>
            </div>
        </>
    )
}

export default Layout